version: '3.8'

services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    platform: linux/arm64
    depends_on:
      - ollama
    networks:
      - ai-network

  ollama:
    image: ollama/ollama:latest
    platform: linux/arm64
    volumes:
      - ~/.ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge